# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CommunityService

on:
  push:
    branches: [ "prod-community" ]
  pull_request:
    branches: [ "prod-community" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Make application.yml
        run: |
          cd BE-Community-Server
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_COMMUNITY }}" > src/main/resources/application.yml
        env:
          APPLICATION: ${{ secrets.APPLICATION_COMMUNITY }}
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
  
      - name: Build with Gradle
        run: ./gradlew build -x test
  
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t app .
          docker tag app ${{ secrets.DOCKER_USERNAME }}/community:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/community:latest
      
      - name: docker-compose.yml 
        uses: appleboy/scp-action@master
        with:
            username: ec2-user
            host: ${{ secrets.HOST }}
            key: ${{ secrets.PRIVATE_KEY_3 }}
            port: ${{ secrets.PORT }}
            source: "./docker-compose-community.yml"
            target: "/home/ec2-user/"
            
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD_3 }} 
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY_3 }} 
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/community:latest
            docker image prune -a -f
            docker-compose up -d
